config/routes.rb
Rails.application.routes.draw do
	post "versions/:id/revert" => "versions#revert", :as => "revert_version"
	devise_for :users
	resources :items do
		member do
			
			patch :complete
			
		end

	end
	root 'items#index'
		get '/about' => 'pages#about'
		get '/contact' => 'pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
    belongs_to :user
    has_many :versions
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	has_many :versions
	has_paper_trail on: [:destroy] # you can pass various options here
	def completed?
		!completed_at.blank?
	end
	validates :title, presence: true, length: {minimum: 6, maximum: 100}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  has_many :categories
  belongs_to :version
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/version.rb
class Version < ApplicationRecord
    has_many :items
    has_many :categories
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_paper_trail_whodunnit
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :update, :destroy]

	def index
		if user_signed_in?
			@items = Item.where(:user_id => current_user.id).order("created_at DESC")
	#	else
		#	@category_id = Category.find_by(name: params[:category]).id
		#	@items = Item.where(:category_id => @category_id).order("Created_at DESC")
		end
	end

	def show
	end

	def new
		@item = current_user.items.build
		@genres = Category.all.map{|c| [c.name, c.id]}
	end

	def create
		@item = current_user.items.build(item_params)
		if @item.save
			redirect_to root_path, :notice =>  "Congrats! Task was created!"
		else
			render 'new' 
		end
	end

	def edit
	end

	def update
		if @item.update(item_params)
			redirect_to item_path(@item), :notice =>  "Congrats! Task was updated!"
			undo_link = view_context.link_to("")
		else
			render 'edit'
		end
	end

	def destroy
		@item.destroy
		redirect_to root_path , :notice => "Task was Deleted! To Revert click. "#{undo_link}
	end

	def complete
		@item = Item.find(params[:id])
		@item.update_attribute(:completed_at, Time.now)
		redirect_to root_path  , :notice => "To undo completed task please click" #{undo_link}"
		
	end
	

	private
	
	def item_params
		params.require(:item).permit(:title, :description)
	end

	def find_item
		@item = Item.find(params[:id])
	end
	# def undo_link
	# 	view_context.link_to("undo",revert_version_path(@item.versions.scope.last), :method => :post)
	# end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
		def about
		end
		
		def contact
		end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
		PaperTrail::Version.where('created_at < ?', 1.day.ago).delete_all
		def revert
			@item = Item.find(params[:id])
			if @item.blank?
			format.html {redirect_to(rooth_path, :notice => 'Record not found') }
			elsif @item.reify
			@item.reify.save!
			else
			@item.item.destroy
			end
			link_name = params[:redo] == "true" ? "undo" : "redo"
			link = view_context.link_to(link_name, revert_version_path(@item.next, :redo => !params[:redo]), :method => :post)
			redirect_to :back, :notice => "Undid #{@item.event}. #{link}"
		end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/items/_form.html.erb
<div class="col-md-8 col-md-offset-2">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading"> 
            <div class="panel-body">
                <div class="container ">
                    <%= simple_form_for @item do |f| %>
                    <div class="form-group row">
                        <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a Category" }, input_html: { class: "dropdown-toggle" } %>
                    </div>
                    <div class="form-group row">
                        <div class="col-10">
                            <%= f.input :title, class: "shadow p-3 mb-3 bg-info rounded" %>
                        </div>
                    </div>

                    <div class="form-group row">
                        <%= f.input :description,  class: "col-2 col-form-label text-light form-control shadow rounded", placeholder: "Description of Task"%>
                        <div class="col-10">
                        </div>
                    </div>
                    <div class="form-group row justify-content-center">
                        <%= f.button :submit, "Create Task", class: "btn btn-info"%>
                    </div>
                    <% end %>
                </div>
                <div cass="mb-3">
                    <%= link_to '[ Cancel ]', items_path, class: "text-info" %>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

app/views/items/_welcome_page.html.erb
<div class="jumbotron">
	<h2>Get it on your list! Before you forget!</h2>
	<br>
	<h4>I was going to do something, then I got distracted for 5seconds and FORGOT!  </h4>	
	</br>
	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-danger" %>
</div>

app/views/items/edit.html.erb
<h1 class= "text-center mt-4"> Edit Task </h1>
	<%= render 'form' %>
</div>

app/views/items/index.html.erb
<!-- Checks to see if a user is signed in, if one is, it will list its checklist. -->
<!-- If not, it will render the landing page that asks the user to sign up or login. -->
<% if user_signed_in? %>
<div class="col-md-10 col-md-offset-3">
        <div class="col-md-2">
            <% if user_signed_in? %>
            <%= link_to "Create To do", new_item_path, class: "btn btn-info" %>
            <% end %>
        </div>
    </div>
    
	<div class="col-md-10 col-md-offset-1">
		<% @items.each do |item| %> 
			<div class="index-wrapper">
				
				<% if item.completed? %>
<!-- For Completed Items-->
					<div class="row item">

						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>
	
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>

						<div class="col-md-8">
							<h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2>
							<p style="opacity: 0.5;" class="item-sub-title item-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at item-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
						</div>
					

		<% else %>
<!-- For Items NOT Completed -->

					<div class="row item">

						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>

						<div class="col-md-8">
							<h2 class="item-title"><%= link_to item.title, item %></h2>
							<p class="item-sub-title item-desc"><%= item.description %></p>
							<p style="opacity: 0.5;" class="time-created-at item-sub-title">Created <%= time_ago_in_words(item.created_at) %> ago</p>
						</div>
						
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>
					</div>

				<% end %>
			</div>
			<div id= "container">	
							<% flash.each do |name,msg| %> 
							<%= content_tag :div, raw(msg), :id => "flash_#{name}" %>
							<%end%>
							<%= content_tag :h2, yield(:title) if new_item_path %>
							</div>
			</div>
		<% end %>	
	 <div class="col-md-10 col-md-offset-3">
        <div class="col-md-2">
            <%= image_tag("image.png", :alt => "rss feed") %>
        </div>
    </div>
	</div>

<% else %>
	<%= render 'welcome_page' %>
	<div class="col-md-10 col-md-offset-1 center">
	<%= image_tag("task.jpg", :alt => "rss feed") %>
	</div>
<% end %>	

app/views/items/new.html.erb
<h1 class= "text-center mt-4"> Task </h1>
<%= render 'form' %>

app/views/items/show.html.erb
<div class="col-md-10 col-md-offset-1">
	<h2><%= @item.title %></h2>
	<p><%= @item.description %></p>

	<div class="col-md-4 col-md-offset-4">
		<%= link_to "Back", root_path , class: "btn btn-success" %>
		<%= link_to "Edit", edit_item_path(@item), class: "btn btn-info" %>
		<%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure?" } , class: "btn btn-danger" %>
	</div>

</div>

app/views/layouts/_footer.html.erb
   <footer id ="sticky-footer" class="footer py-4 bg-dark text-white">
        <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Stephen's Github", "https://github.com/stephenh0191", class: "text-white" %> </small>
        </div>
    </footer>

app/views/layouts/_navigation.html.erb
<div class="container">
        <% if current_user.present? %>
        <div class="dropdown">
            <li class=current_user>
                <button class="dropbtn">Welcome</button>
                <div class="dropdown-content">
                    <ul>
                        <li class='login'><%= link_to "Edit Account",  edit_user_registration_path %></li>
                        <li class='login'><%= link_to "About", about_path %></li>
                        <li class='login'><%= link_to "contact", contact_path %></li>
                        <li class="dropdown-divider"></li>
                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                </div>
            </li>
        </div>
        <% else %>
        <li><%= link_to "Log In", new_user_session_path , class: "btn btn-danger"%></li>
        <% end %>
        </ul>
    </div>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                 <%= link_to "It's on my List", root_path, class:"navbar-brand"  %>
            </div>
    </nav>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>ItsOnmylist</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div class="container">
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">	
	<div class="jumbotron">
		<h2>Welcome</h2>
		<br>
		<h4>This Application is for your everday tasks be it at your office or at home. 
			Simple and easy to use. You won't forget </h4>
		</br>
	</div>
	<%= link_to "Back to your todo list", items_path, class: "btn btn-success"%>

	<div class="col-md-10 col-md-offset-1 center">
	<div class="col-md-2">
		<%= image_tag("task.jpg", :alt => "rss feed") %>
	</div>
	</div>
</div>

app/views/pages/contact.html.erb
<div id="page_wrapper">	
	<div class="jumbotron">
		<h2>Get in touch</h2>
		<br>
		<h4> Any ideas or tricks and tips let me know </h4>
		</br>
	</div>
	<%= link_to "Back to your todo list", items_path, class: "btn btn-success"%>

	<div class="col-md-10 col-md-offset-1 center">
	<div class="col-md-2">
		<%= image_tag("task.jpg", :alt => "rss feed") %>
	</div>
	</div>
</div>